repos:
-   repo: https://github.com/ambv/black
    rev: '21.5b1'
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
    -   id: mypy
        additional_dependencies:
        -   pydantic>=1.8.1
