repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  # Mypy config
  # Note that we have to specify exclusions here. This is because mypy's exclude setting
  # gets overridden by the actual path spec.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.0.1'
    hooks:
      - id: mypy
        additional_dependencies:
          # These have to be installed here as well as in the venv if you want to be able
          # to run `mypy splitgraph` from the commandline.
          - pydantic>=1.8.1
          - types-chardet
          - types-requests
          - types-tabulate
          - types-PyYAML
        exclude: "^(examples|test|docs)/"

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        language_version: python3
        types_or: [cython, pyi, python]
        args: ["--profile", "black", "--filter-files"]
        minimum_pre_commit_version: "2.9.2"
        additional_dependencies: ["isort==5.10.1"]
