language: python
install: true
sudo: required
python:
  - "3.6"
install:
  - poetry install
script:
  - poetry run pytest

services:
  - docker

addons:
  hosts:
    # We need both the host and the local driver to be able to refer to the remote driver
    # using the same connection string, hence we map remote_driver on the host to localhost
    # (Docker networking takes care of wiring it up in the case of the container)
    - remote_driver

env:
  COMPOSE_VERSION: 1.21.2

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - pip install poetry

before_script:
  # Stop the PG/MySQL that ship with Travis and run our own integration test
  # SG driver/remote architecture instead.
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/mysql stop
  - sudo docker-compose --file test/architecture/docker-compose.yml up -d pgorigin mongoorigin mysqlorigin local_driver remote_driver object_storage remote_server
  - ./wait-for-test-architecture.sh

after_success:
  - poetry run coveralls
