python_tests(
    name="tests",
    skip_mypy=True,
    skip_black=True,
    skip_pyupgrade=True,
)

python_test_utils(
    name="test_utils",
    overrides={"conftest.py": {"skip_mypy": True, "skip_black": True}},
)

python_sources(
    skip_mypy=True,
    skip_black=True,
    skip_pyupgrade=True,
)
