version: '3'
services:
  engine:
    image: splitgraph/engine:${DOCKER_TAG-stable}
    ports:
      - '0.0.0.0:5432:5432'
    environment:
      - POSTGRES_USER=sgr
      - POSTGRES_PASSWORD=supersecure
      - POSTGRES_DB=splitgraph
      - SG_LOGLEVEL=INFO
    # Both the engine and the origin database have to be started with
    # wal_level=logical (logical WAL decoding enabled).
    command:
      - -c
      - 'wal_level=logical'
    expose:
      - 5432
  origin:
    image: postgres:12
    ports:
      - '0.0.0.0:5431:5432'
    command:
      - -c
      - 'wal_level=logical'
    environment:
      - POSTGRES_USER=originuser
      - POSTGRES_PASSWORD=originpass
    volumes:
      - ./origin/000_initial_data.sql:/docker-entrypoint-initdb.d/000_initial_data.sql
