version: "3.4"
services:
  # Splitgraph engine: we'll be inheriting from the main engine and adding the FDW to it.
  engine:
    build:
      context: ./src
      dockerfile: engine.Dockerfile
    environment:
      - POSTGRES_USER=sgr
      - POSTGRES_PASSWORD=supersecure
      - POSTGRES_DB=splitgraph
      - SG_LOGLEVEL=INFO
      - SG_CONFIG_FILE=/.sgconfig
    # Bind mount the Python source code so that it can be edited without having to rebuild
    # the images.
    volumes:
      - ./src/hn_fdw:/hn_fdw/hn_fdw

  # Container with the sgr client.
  sgr:
    build:
      context: ./src
      dockerfile: sgr.Dockerfile
    depends_on:
      - engine
    environment:
      - SG_CONFIG_FILE=/.sgconfig
    volumes:
      - ./src/hn_fdw:/hn_fdw/hn_fdw