version: '3'
services:
  engine:
    image: splitgraph/engine:${DOCKER_TAG-stable}
    ports:
      - '0.0.0.0:5432:5432'
    environment:
      - POSTGRES_USER=sgr
      - POSTGRES_PASSWORD=supersecure
      - POSTGRES_DB=splitgraph
      - SG_LOGLEVEL=INFO
    expose:
      - 5432
  mongo:
    build: ./splitgraph/mongodb
    environment:
      - ORIGIN_USER=originro
      - ORIGIN_PASS=originpass
      - ORIGIN_MONGO_DB=origindb
    expose:
      - 27017
    volumes:
      - ./splitgraph/mongodb/setup.js:/src/setup.js
  postgres:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=originuser
      - POSTGRES_PASSWORD=originpass
      - POSTGRES_DB=origindb
    expose:
      - 5432
    volumes:
      - ./splitgraph/postgresql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
