version: '3'
services:
  engine:
    image: splitgraph/engine:${DOCKER_TAG-stable-postgis}
    ports:
      - '0.0.0.0:5432:5432'
    environment:
      - POSTGRES_USER=sgr
      - POSTGRES_PASSWORD=supersecure
      - POSTGRES_DB=splitgraph
      - SG_LOGLEVEL=INFO
      - SG_CONFIG_FILE=/.sgconfig
    expose:
      - 5432
    volumes:
      - ./.sgconfig:/.sgconfig
  pgadmin:
    image: dpage/pgadmin4:4.21
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./pgadmin/pgpassfile:/tmp/pgpassfile
      - ./pgadmin/servers.json:/tmp/servers.json
